"""empty message

Revision ID: 537657eb4f80
Revises: 108372ce08f1
Create Date: 2018-03-27 20:27:00.434000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537657eb4f80'
down_revision = '108372ce08f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.add_column(u'users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column(u'users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'name')
    op.drop_column(u'users', 'member_since')
    op.drop_column(u'users', 'location')
    op.drop_column(u'users', 'last_seen')
    op.drop_column(u'users', 'about_me')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
